[pytest]

markers =
        SCL_create_checkbox: mark a test as SCL_create_checkbox
        SCL_set_text_checkbox: mark a test as SCL_set_text_checkbox
        SCL_list_select_checkboxes: mark a test as SCL_list_select_checkboxes