[pytest]

markers =
        SCL_create_checkbox: mark a test as SCL_create_checkbox
        SCL_set_text_checkbox: mark a test as SCL_set_text_checkbox
        SCL_list_select_checkboxes: mark a test as SCL_list_select_checkboxes
        SCL_list_text_select_checkboxes: mark a test as SCL_list_text_select_checkboxes
        SCL_delete_checkbox: mark a test as SCL_delete_checkbox
        SCL_check_select_checkboxes